import { BrainCircuit, CheckCircle2, RefreshCw } from 'lucide-react'
import { useMutation } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { PageError } from '../../components/PageState'
import type { PersonalizedConstraints, RiskQuestionnaireAnswers } from '../../lib/api/client'
import { useApi } from '../../lib/api/context'
import { savePersonalizedDefaults } from '../../lib/personalization'

const questions = [
  {key:'age_bracket',label:'Age bracket',options:[['under_30','Under 30'],['30_44','30–44'],['45_59','45–59'],['60_plus','60 or above']]},
  {key:'investment_horizon',label:'Investment horizon',options:[['under_3_years','Under 3 years'],['3_5_years','3–5 years'],['6_10_years','6–10 years'],['over_10_years','More than 10 years']]},
  {key:'income_stability',label:'Income stability',options:[['unstable','Unstable'],['variable','Variable'],['stable','Stable'],['highly_stable','Highly stable']]},
  {key:'loss_reaction',label:'Reaction to a temporary 20% loss',options:[['sell_all','Sell all'],['sell_some','Sell some'],['hold','Hold'],['buy_more','Invest more']]},
  {key:'experience_level',label:'Investment experience',options:[['none','None'],['beginner','Beginner'],['intermediate','Intermediate'],['advanced','Advanced']]},
  {key:'financial_dependents',label:'Financial dependents',options:[['three_or_more','Three or more'],['one_or_two','One or two'],['none','None']]},
] as const
const initialAnswers:RiskQuestionnaireAnswers={age_bracket:'30_44',investment_horizon:'6_10_years',income_stability:'stable',loss_reaction:'hold',experience_level:'intermediate',financial_dependents:'one_or_two'}

export function RiskQuestionnaire(){const api=useApi(),navigate=useNavigate();const[answers,setAnswers]=useState<RiskQuestionnaireAnswers>(initialAnswers),[constraints,setConstraints]=useState<PersonalizedConstraints|null>(null);const mutation=useMutation({mutationFn:()=>api.submitRiskProfile(answers),onSuccess:profile=>setConstraints(profile.recommended_constraints)});const submit=(event:FormEvent)=>{event.preventDefault();mutation.mutate()};const proceed=()=>{if(!mutation.data||!constraints)return;savePersonalizedDefaults({...constraints,category:mutation.data.predicted_category,confidence:mutation.data.category_confidence});navigate('/builder')};return <main className="auth-page onboarding-page"><section className="card onboarding-card"><div className="card-head"><div><span>PERSONALIZED ONBOARDING</span><h2>Find your starting risk profile</h2></div><BrainCircuit/></div><p className="onboarding-note">This ML model learns a transparent questionnaire rubric—not real investor outcomes. Its recommendation pre-fills editable optimization controls.</p>{mutation.error&&<PageError error={mutation.error} retry={()=>mutation.mutate()}/>} {!mutation.data?<form className="questionnaire-grid" onSubmit={submit}>{questions.map(question=><label key={question.key}>{question.label}<select aria-label={question.label} value={answers[question.key]} onChange={event=>setAnswers({...answers,[question.key]:event.target.value})}>{question.options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>)}<button className="primary" disabled={mutation.isPending}>{mutation.isPending?<><RefreshCw className="spin"/>Assessing profile…</>:<>Get transparent recommendation</>}</button></form>:<div className="recommendation"><CheckCircle2/><p>Based on your answers, we suggest a <strong>{mutation.data.predicted_category}</strong> risk profile with {(mutation.data.category_confidence*100).toFixed(1)}% rubric-classification confidence.</p><small>These values remain fully editable before optimization.</small><div className="constraint-editor"><label>Risk tolerance<input aria-label="Recommended risk tolerance" type="number" min="0.01" max="1" step="0.01" value={constraints!.risk_tolerance} onChange={e=>setConstraints({...constraints!,risk_tolerance:Number(e.target.value)})}/></label><label>Maximum stock weight<input aria-label="Recommended maximum stock weight" type="number" min="0.01" max="1" step="0.01" value={constraints!.max_single_weight} onChange={e=>setConstraints({...constraints!,max_single_weight:Number(e.target.value)})}/></label><label>Default sector cap<input aria-label="Recommended default sector cap" type="number" min="0.01" max="1" step="0.01" value={constraints!.default_sector_cap} onChange={e=>setConstraints({...constraints!,default_sector_cap:Number(e.target.value)})}/></label></div><button className="primary" onClick={proceed}>Use these editable defaults</button></div>}</section></main>}
