from __future__ import annotations

from html.parser import HTMLParser

import pytest

from app.reports.context_builder import ReportContext
from app.reports.pdf_renderer import render_html

DISCLAIMER = (
    "This report is generated by an academic decision-support system for educational "
    "purposes. It is not personalized investment advice. Past performance and backtested "
    "results do not guarantee future returns. Consult a registered investment advisor "
    "before making investment decisions."
)


class DocumentParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.html_elements = 0

    def handle_starttag(self, tag: str, attrs) -> None:
        if tag == "html":
            self.html_elements += 1


@pytest.mark.parametrize(
    "template_name",
    [
        "summary.html.jinja",
        "optimization_report.html.jinja",
        "recommendation.html.jinja",
    ],
)
def test_every_template_is_valid_html_and_contains_shared_content(
    template_name: str,
    report_context: ReportContext,
) -> None:
    html = render_html(template_name, report_context)
    parser = DocumentParser()
    parser.feed(html)
    assert html.lstrip().casefold().startswith("<!doctype html>")
    assert parser.html_elements == 1
    assert DISCLAIMER in html
    assert "IN-SAMPLE FIT" in html
    assert "OUT-OF-SAMPLE BACKTEST" in html
    assert "The windows overlap:\n  no" in html
    for holding in report_context.holdings:
        assert holding.symbol in html


def test_disclaimer_exists_only_in_shared_partial() -> None:
    from app.reports.pdf_renderer import TEMPLATE_DIRECTORY

    partial = (TEMPLATE_DIRECTORY / "_disclaimer.html.jinja").read_text(encoding="utf-8")
    assert DISCLAIMER in partial
    for template_name in (
        "summary.html.jinja",
        "optimization_report.html.jinja",
        "recommendation.html.jinja",
    ):
        source = (TEMPLATE_DIRECTORY / template_name).read_text(encoding="utf-8")
        assert '{% include "_disclaimer.html.jinja" %}' in source
        assert DISCLAIMER not in source
