import { Activity, BriefcaseBusiness, Gauge, Sparkles, TrendingUp } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { useApi } from '../lib/api/context'
import { money, number, percent } from '../lib/format'
import { Metric } from '../components/Metric'
import { EmptyState, PageError, PageLoading } from '../components/PageState'

export function DashboardPage(){const api=useApi();const query=useQuery({queryKey:['portfolios'],queryFn:()=>api.portfolios()});if(query.isLoading)return <PageLoading label="Loading your live portfolios…"/>;if(query.error)return <PageError error={query.error} retry={()=>query.refetch()}/>;const portfolios=query.data??[];const active=portfolios.filter(p=>p.is_active);const snapshots=portfolios.flatMap(p=>p.latest_snapshot?[{portfolio:p,snapshot:p.latest_snapshot}]:[]);const total=snapshots.reduce((sum,x)=>sum+(x.snapshot.budget_inr??0),0);const latest=snapshots[0]?.snapshot;return <><section className="hero-row"><div><p className="eyebrow">LIVE DECISION WORKSPACE</p><h2>Your portfolios</h2><p>Metrics below come directly from persisted optimization snapshots.</p></div><Link className="primary" to="/builder"><Sparkles/>Run new optimization</Link></section><section className="metric-grid"><Metric label="INVESTED CAPITAL" value={money(total)} detail={`${active.length} active portfolios`} icon={BriefcaseBusiness}/><Metric label="EXPECTED RETURN" value={percent(latest?.expected_return)} detail="Latest optimized snapshot" icon={TrendingUp}/><Metric label="ANNUAL VOLATILITY" value={percent(latest?.expected_volatility)} detail="Model estimate" icon={Activity}/><Metric label="SHARPE RATIO" value={number(latest?.sharpe_ratio)} detail="Risk-adjusted return" icon={Gauge}/></section><section className="card live-list"><div className="card-head"><div><span>RECENT ACTIVITY</span><h3>Persisted portfolios and optimization snapshots</h3></div></div>{portfolios.length===0?<EmptyState>No portfolio exists yet. Start in Portfolio Builder.</EmptyState>:portfolios.map(p=><div className="live-row" key={p.id}><div><strong>{p.name}</strong><small>Created {new Date(p.created_at).toLocaleString('en-IN')}</small></div><span>{p.latest_snapshot?`${p.latest_snapshot.holding_count??0} holdings · ${percent(p.latest_snapshot.expected_return)}`:'Awaiting optimization'}</span><Link className="text-btn" to={p.latest_snapshot?`/portfolio/${p.id}/${p.latest_snapshot.id}`:`/builder?portfolio=${p.id}`}>Open</Link></div>)}</section></>}
