import { BookOpen, BrainCircuit, BriefcaseBusiness, Download } from 'lucide-react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { EmptyState, PageError, PageLoading } from '../components/PageState'
import { useApi } from '../lib/api/context'
import { loadSelection } from '../lib/selection'

const templates=[{type:'portfolio_summary',title:'Portfolio summary',description:'Allocation, forecast metrics, sector exposure, and investor profile.',icon:BriefcaseBusiness},{type:'optimization_report',title:'Optimization report',description:'Objective, active constraints, solver outcome, and asset rationale.',icon:BrainCircuit},{type:'investment_recommendation',title:'Investment recommendation',description:'Explainable, audit-ready decision summary and disclaimer.',icon:BookOpen}] as const

export function ReportsPage(){const api=useApi(),cache=useQueryClient(),selected=loadSelection();const reports=useQuery({queryKey:['reports'],queryFn:()=>api.reports()});const generate=useMutation({mutationFn:(type:string)=>{if(!selected)throw new Error('Optimize and select a portfolio first.');return api.generateReport(selected.portfolioId,selected.snapshotId,type)},onSuccess:()=>cache.invalidateQueries({queryKey:['reports']})});const download=async(id:string)=>{const blob=await api.downloadReport(id);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60_000)};if(reports.isLoading)return <PageLoading label="Loading generated report history…"/>;if(reports.error)return <PageError error={reports.error} retry={()=>reports.refetch()}/>;return <><section className="page-intro"><div><p className="eyebrow">REAL PHASE 8 PDF SERVICE</p><h2>Reporting centre</h2><p>Every PDF is rendered from the selected persisted snapshot and real analytics bundle.</p></div></section>{generate.error&&<PageError error={generate.error}/>}<section className="report-grid">{templates.map(template=><div className="card report" key={template.type}><div className="report-icon"><template.icon/></div><h3>{template.title}</h3><p>{template.description}</p><div className="report-preview"><div/><div/><div/><div/></div><button className="primary" disabled={generate.isPending} onClick={()=>generate.mutate(template.type)}><Download/>{generate.isPending?'Generating PDF…':'Generate real PDF'}</button></div>)}</section><section className="card live-list"><div className="card-head"><div><span>REPORT HISTORY</span><h3>Generated PDFs</h3></div></div>{reports.data?.length===0?<EmptyState>No reports generated yet.</EmptyState>:reports.data?.map(report=><div className="live-row" key={report.id}><div><strong>{report.report_type.replaceAll('_',' ')}</strong><small>{report.generated_at?new Date(report.generated_at).toLocaleString('en-IN'):report.file_path}</small></div><span>{report.size_bytes?`${Math.ceil(report.size_bytes/1024)} KiB`:'PDF'}</span><button className="secondary" onClick={()=>download(report.id)}><Download/>Open</button></div>)}</section></>}
