import { useMemo, useState } from 'react'
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, Bell, BookOpen, BrainCircuit, BriefcaseBusiness, Check, ChevronDown, CircleHelp, Download, Gauge, LayoutDashboard, Menu, RefreshCw, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Target, TrendingUp, TriangleAlert, X, Zap } from 'lucide-react'
import { benchmark, curve, holdings, type Holding } from './data'

type Page = 'Overview' | 'Optimizer' | 'Scenarios' | 'Analytics' | 'Reports'
const money = (n:number) => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)

function LineChart({stress=0}:{stress?:number}) {
  const w=760,h=260,p=18
  const adjusted=curve.map((v,i)=> v-(i>14 ? stress*(i-14)/15 : 0))
  const points=(data:number[])=>data.map((v,i)=>`${p+i*(w-p*2)/(data.length-1)},${h-p-(v-95)*(h-p*2)/40}`).join(' ')
  return <div className="chart-wrap"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Portfolio performance chart">
    <defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#39e6a1" stopOpacity=".24"/><stop offset="1" stopColor="#39e6a1" stopOpacity="0"/></linearGradient></defs>
    {[0,1,2,3,4].map(i=><line key={i} x1={p} y1={p+i*52} x2={w-p} y2={p+i*52} stroke="#ffffff" strokeOpacity=".055" />)}
    <polygon points={`${p},${h-p} ${points(adjusted)} ${w-p},${h-p}`} fill="url(#area)" />
    <polyline points={points(benchmark)} fill="none" stroke="#64748b" strokeWidth="2" strokeDasharray="5 7" />
    <polyline points={points(adjusted)} fill="none" stroke="#39e6a1" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round" />
    <circle cx={w-p} cy={Number(points(adjusted).split(' ').at(-1)?.split(',')[1])} r="4" fill="#39e6a1" stroke="#0b0e12" strokeWidth="3"/>
  </svg><div className="chart-axis"><span>Aug</span><span>Oct</span><span>Dec</span><span>Feb</span><span>Apr</span><span>Jun</span></div></div>
}

function Donut({items=holdings}:{items?:Holding[]}) {
  const gradient=items.reduce<{cursor:number;segments:string[]}>((acc,h)=>({cursor:acc.cursor+h.weight,segments:[...acc.segments,`${h.color} ${acc.cursor}% ${acc.cursor+h.weight}%`]}),{cursor:0,segments:[]}).segments.join(',')
  return <div className="donut" style={{background:`conic-gradient(${gradient})`}}><div><strong>{items.length}</strong><span>holdings</span></div></div>
}

function Sidebar({page,setPage,open,setOpen}:{page:Page,setPage:(p:Page)=>void,open:boolean,setOpen:(v:boolean)=>void}) {
  const links:[[Page,typeof LayoutDashboard],...Array<[Page,typeof LayoutDashboard]>]=[['Overview',LayoutDashboard],['Optimizer',SlidersHorizontal],['Scenarios',Zap],['Analytics',BarChart3],['Reports',BookOpen]]
  return <aside className={open?'sidebar open':'sidebar'}>
    <div className="brand"><div className="brand-mark"><TrendingUp size={19}/></div><span>OptiVest</span><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button></div>
    <p className="side-label">WORKSPACE</p>
    <nav>{links.map(([label,Icon])=><button key={label} className={page===label?'nav-link active':'nav-link'} onClick={()=>{setPage(label);setOpen(false)}}><Icon size={18}/><span>{label}</span>{label==='Optimizer'&&<em>LIVE</em>}</button>)}</nav>
    <div className="sidebar-bottom"><div className="system-card"><div><span className="pulse"/>SYSTEM STATUS</div><strong>All models operational</strong><small>Market data · 2 min ago</small></div><button className="nav-link"><CircleHelp size={18}/>Help & documentation</button><button className="profile"><div>PC</div><span><strong>Parth Chandurkar</strong><small>Research workspace</small></span><ChevronDown size={16}/></button></div>
  </aside>
}

function Topbar({page,onMenu}:{page:Page,onMenu:()=>void}) {return <header><button className="menu" onClick={onMenu}><Menu/></button><div><span className="crumb">PORTFOLIO INTELLIGENCE</span><h1>{page}</h1></div><div className="top-actions"><div className="market"><span className="pulse"/>MARKET OPEN <b>NIFTY 50</b> 24,367.50 <em>+0.84%</em></div><button aria-label="Search"><Search/></button><button aria-label="Notifications" className="notification"><Bell/><i/></button></div></header>}

function Metric({label,value,delta,icon:Icon,negative=false}:{label:string,value:string,delta:string,icon:typeof Activity,negative?:boolean}) {return <div className="metric card"><div className="metric-top"><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><small className={negative?'bad':'good'}>{negative?<ArrowDownRight/>:<ArrowUpRight/>}{delta}</small></div>}

function Overview({setPage}:{setPage:(p:Page)=>void}) {return <>
  <section className="hero-row"><div><p className="eyebrow">THURSDAY, 13 AUGUST</p><h2>Good morning, Parth.</h2><p>Your optimized portfolio is outperforming the benchmark by <b>12.4%</b> this year.</p></div><button className="primary" onClick={()=>setPage('Optimizer')}><Sparkles size={17}/>Run new optimization</button></section>
  <section className="metric-grid"><Metric label="PORTFOLIO VALUE" value="₹25,00,000" delta="₹3,14,250 (14.4%) YTD" icon={BriefcaseBusiness}/><Metric label="EXPECTED RETURN" value="16.8%" delta="2.1% vs benchmark" icon={TrendingUp}/><Metric label="ANNUAL VOLATILITY" value="19.6%" delta="3.2% below NIFTY" icon={Activity}/><Metric label="SHARPE RATIO" value="1.42" delta="Top 18th percentile" icon={Gauge}/></section>
  <section className="main-grid"><div className="card performance"><div className="card-head"><div><span>PERFORMANCE</span><h3>Growth of ₹100</h3></div><div className="periods"><button>1M</button><button>3M</button><button>6M</button><button className="selected">1Y</button><button>ALL</button></div></div><div className="legend"><span><i className="portfolio-dot"/>OptiVest <b>+29.4%</b></span><span><i/>NIFTY 50 <b>+17.0%</b></span></div><LineChart/></div>
  <div className="card allocation"><div className="card-head"><div><span>ALLOCATION</span><h3>Portfolio composition</h3></div><button onClick={()=>setPage('Analytics')} className="text-btn">View all <ArrowRight/></button></div><div className="allocation-body"><Donut/><div className="alloc-list">{holdings.slice(0,5).map(h=><div key={h.symbol}><i style={{background:h.color}}/><span>{h.symbol}<small>{h.sector}</small></span><b>{h.weight}%</b></div>)}</div></div><div className="div-score"><span><ShieldCheck/>Diversification score</span><b>86 <small>/ 100</small></b></div></div></section>
  <section className="lower-grid"><div className="card insights"><div className="card-head"><div><span>DECISION INTELLIGENCE</span><h3>What changed this week</h3></div><BrainCircuit/></div><div className="insight-row"><div className="insight-icon positive"><TrendingUp/></div><div><strong>Technology allocation increased</strong><p>INFY's improving risk-adjusted return added 2.4% to its target weight.</p></div><b>+2.4%</b></div><div className="insight-row"><div className="insight-icon warning"><TriangleAlert/></div><div><strong>Financials constraint is binding</strong><p>Sector allocation reached your 30% limit, restricting ICICIBANK.</p></div><span>BINDING</span></div></div>
  <div className="card risk"><div className="card-head"><div><span>RISK BUDGET</span><h3>Volatility utilization</h3></div><Target/></div><div className="risk-number"><strong>19.6%</strong><span>of 24.0% limit</span></div><div className="progress"><i style={{width:'81.7%'}}/></div><div className="risk-scale"><span>Conservative</span><span>4.4% headroom</span><span>Limit</span></div><button className="secondary" onClick={()=>setPage('Scenarios')}>Stress-test portfolio <ArrowRight/></button></div></section>
  </>}

function Optimizer({onOptimized}:{onOptimized:()=>void}) {
 const [budget,setBudget]=useState(2500000),[risk,setRisk]=useState(55),[count,setCount]=useState(9),[sector,setSector]=useState(30),[solving,setSolving]=useState(false),[done,setDone]=useState(false)
 const solve=()=>{setSolving(true);setDone(false);setTimeout(()=>{setSolving(false);setDone(true);onOptimized()},1100)}
 return <><section className="page-intro"><div><p className="eyebrow">CONSTRAINED MEAN–VARIANCE MODEL</p><h2>Build an optimal portfolio</h2><p>Define your investment rules. OptiVest searches the feasible set and explains the best allocation.</p></div><div className="model-badge"><span className="pulse"/>PuLP · CBC solver</div></section>
 <section className="optimizer-grid"><div className="card controls"><div className="card-head"><div><span>MODEL INPUTS</span><h3>Investment constraints</h3></div><Settings2/></div>
 <label>Investment capital <div className="input-prefix"><span>₹</span><input value={budget.toLocaleString('en-IN')} onChange={e=>setBudget(Number(e.target.value.replace(/,/g,''))||0)}/></div></label>
 <div className="field"><div><label>Risk tolerance</label><b>{risk<40?'Conservative':risk<70?'Balanced':'Aggressive'}</b></div><input type="range" min="10" max="90" value={risk} onChange={e=>setRisk(+e.target.value)}/><div className="range-labels"><span>Lower risk</span><span>Higher return</span></div></div>
 <div className="two-fields"><label>Holdings <div className="stepper"><button onClick={()=>setCount(Math.max(5,count-1))}>−</button><span>{count}</span><button onClick={()=>setCount(Math.min(20,count+1))}>+</button></div></label><label>Sector cap <div className="stepper"><button onClick={()=>setSector(Math.max(15,sector-5))}>−</button><span>{sector}%</span><button onClick={()=>setSector(Math.min(45,sector+5))}>+</button></div></label></div>
 <div className="constraint-list"><div><Check/>Long-only positions</div><div><Check/>Minimum weight 4%</div><div><Check/>Maximum stock weight 20%</div></div>
 <button className="primary solve" disabled={solving} onClick={solve}>{solving?<><RefreshCw className="spin"/>Solving 50 assets…</>:<><Sparkles/>Optimize portfolio</>}</button></div>
 <div className="card result"><div className="card-head"><div><span>OPTIMAL SOLUTION</span><h3>{done?'Portfolio re-optimized':'Projected allocation'}</h3></div>{done&&<div className="success"><Check/>OPTIMAL</div>}</div><div className="solution-summary"><Donut items={holdings.slice(0,count)}/><div><span>EXPECTED RETURN</span><strong>{(14.6+risk*.04).toFixed(1)}%</strong><small>Annualized projection</small><span>SHARPE RATIO</span><strong>1.42</strong></div></div><div className="result-table"><div className="table-head"><span>ASSET</span><span>WEIGHT</span><span>VALUE</span></div>{holdings.slice(0,count).map(h=><div key={h.symbol}><span><i style={{background:h.color}}/><b>{h.symbol}</b><small>{h.sector}</small></span><span><div className="mini-bar"><i style={{width:`${h.weight*4}%`,background:h.color}}/></div><b>{h.weight}%</b></span><span>{money(budget*h.weight/100)}</span></div>)}</div></div></section></>
}

function Scenarios(){const [shock,setShock]=useState(20); const loss=(shock*0.68).toFixed(1);return <><section className="page-intro"><div><p className="eyebrow">WHAT-IF ANALYSIS</p><h2>Stress-test the decision</h2><p>Apply market shocks and inspect how your portfolio responds before capital is committed.</p></div><button className="secondary"><RefreshCw/>Reset scenario</button></section><div className="scenario-tabs">{['Market crash','Rate hike','Sector shock','Inflation'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div><section className="scenario-grid"><div className="card shock-control"><span>SCENARIO PARAMETERS</span><h3>Broad market decline</h3><div className="shock-value">−{shock}%</div><input type="range" min="5" max="40" value={shock} onChange={e=>setShock(+e.target.value)}/><div className="range-labels"><span>−5%</span><span>−40%</span></div><div className="presets"><button onClick={()=>setShock(10)}>Correction −10%</button><button onClick={()=>setShock(20)} className={shock===20?'selected':''}>Bear market −20%</button><button onClick={()=>setShock(35)}>Severe −35%</button></div><div className="scenario-note"><ShieldCheck/><p><strong>Correlation regime adjustment enabled</strong><br/>Asset correlations increase under market stress.</p></div></div><div className="card stress-result"><div className="card-head"><div><span>PROJECTED RESPONSE</span><h3>Portfolio resilience</h3></div><div className="live"><span className="pulse"/>LIVE</div></div><div className="stress-metrics"><div><span>PORTFOLIO IMPACT</span><strong className="red">−{loss}%</strong><small>{money(-2500000*Number(loss)/100)}</small></div><div><span>VS. NIFTY 50</span><strong className="green">+{(shock-Number(loss)).toFixed(1)}%</strong><small>Downside protection</small></div><div><span>RECOVERY EST.</span><strong>{Math.ceil(shock/3)} mo</strong><small>95% confidence</small></div></div><LineChart stress={shock*.52}/></div></section><section className="card shock-table"><div className="card-head"><div><span>HOLDING IMPACT</span><h3>Stress attribution</h3></div><button className="text-btn">Export analysis <Download/></button></div><div className="table-head"><span>ASSET</span><span>BASE VALUE</span><span>STRESSED RETURN</span><span>LOSS CONTRIBUTION</span><span>NEW WEIGHT</span></div>{holdings.slice(0,6).map((h,i)=><div className="shock-row" key={h.symbol}><span><i style={{background:h.color}}/><b>{h.symbol}</b></span><span>{money(h.value)}</span><span className="red">−{(shock*(.45+i*.07)).toFixed(1)}%</span><span>−{(h.weight*shock*(.45+i*.07)/100).toFixed(2)}%</span><span>{(h.weight*(1+(3-i)*.01)).toFixed(1)}%</span></div>)}</section></>}

function Analytics(){return <><section className="page-intro"><div><p className="eyebrow">PORTFOLIO DIAGNOSTICS</p><h2>Understand every allocation</h2><p>Trace portfolio risk, return, diversification, and the model's reasoning at holding level.</p></div><button className="secondary"><Download/>Export data</button></section><section className="metric-grid"><Metric label="ALPHA" value="+4.6%" delta="vs NIFTY 50" icon={TrendingUp}/><Metric label="BETA" value="0.82" delta="18% less market risk" icon={Activity}/><Metric label="MAX DRAWDOWN" value="−12.8%" delta="5.4% better" icon={ArrowDownRight}/><Metric label="SORTINO RATIO" value="1.87" delta="Strong downside efficiency" icon={Gauge}/></section><section className="analytics-grid"><div className="card"><div className="card-head"><div><span>SECTOR EXPOSURE</span><h3>Allocation by sector</h3></div></div><div className="sector-bars">{[['Financials',30,'#60a5fa'],['Technology',13.6,'#a78bfa'],['Energy',15.2,'#34d399'],['Industrials',10.4,'#fb7185'],['Healthcare',9.2,'#22d3ee'],['Other',21.6,'#64748b']].map(([s,v,c])=><div key={s as string}><span>{s}</span><div><i style={{width:`${Number(v)*2.8}%`,background:c as string}}/></div><b>{v}%</b></div>)}</div></div><div className="card"><div className="card-head"><div><span>RISK–RETURN MAP</span><h3>Efficient positioning</h3></div></div><div className="scatter"><span className="axis-y">Expected return →</span>{holdings.map((h,i)=><button title={`${h.symbol}: ${h.expectedReturn}% return`} style={{left:`${15+(h.volatility-15)*4.3}%`,bottom:`${16+(h.expectedReturn-13)*9}%`,background:h.color,width:12+h.weight,height:12+h.weight}} key={h.symbol}>{i<4&&<em>{h.symbol}</em>}</button>)}<span className="axis-x">Annualized volatility →</span></div></div></section><section className="card explanations"><div className="card-head"><div><span>EXPLAINABILITY ENGINE</span><h3>Why these assets were selected</h3></div><BrainCircuit/></div>{holdings.map((h,i)=><div className="explanation" key={h.symbol}><div className="rank">{String(i+1).padStart(2,'0')}</div><div className="ticker"><i style={{background:h.color}}/><span><b>{h.symbol}</b><small>{h.name}</small></span></div><p>{h.rationale}</p><div className="model-score"><span>MODEL SCORE</span><b>{h.score}</b></div></div>)}</section></>}

function Reports(){const [toast,setToast]=useState(false);const download=()=>{const content=`OPTIVEST — OPTIMIZATION REPORT\nGenerated: 13 August 2026\n\nPortfolio value: ₹25,00,000\nExpected return: 16.8%\nVolatility: 19.6%\nSharpe ratio: 1.42\n\nHOLDINGS\n${holdings.map(h=>`${h.symbol}\t${h.weight}%\t₹${h.value}`).join('\n')}\n\nMethodology: constrained mean-variance optimization with sector, cardinality, and risk-budget limits.`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/plain'}));a.download='OptiVest-Optimization-Report.txt';a.click();setToast(true);setTimeout(()=>setToast(false),2500)};return <><section className="page-intro"><div><p className="eyebrow">REPORTING CENTRE</p><h2>Document the decision</h2><p>Generate clear, audit-ready summaries of the model, constraints, outcomes, and recommendations.</p></div></section><section className="report-grid">{[{icon:BriefcaseBusiness,title:'Portfolio summary',desc:'Allocation, forecast metrics, sector exposure, and investor profile.',tag:'8 pages'},{icon:BrainCircuit,title:'Optimization report',desc:'Objective function, active constraints, solver outcome, and asset rationale.',tag:'12 pages'},{icon:Zap,title:'Stress-test report',desc:'Scenario assumptions, loss attribution, resilience, and recovery estimates.',tag:'6 pages'}].map((r,i)=><div className="card report" key={r.title}><div className="report-icon"><r.icon/></div><span>{r.tag}</span><h3>{r.title}</h3><p>{r.desc}</p><div className="report-preview"><div/><div/><div/><div/></div><button className={i===1?'primary':'secondary'} onClick={download}><Download/>Generate report</button></div>)}</section><div className="card methodology"><div><BookOpen/><span><strong>Methodology appendix</strong><small>Include model definitions, assumptions, data provenance, and constraint glossary.</small></span></div><label className="toggle"><input type="checkbox" defaultChecked/><i/></label></div>{toast&&<div className="toast"><Check/>Report downloaded successfully</div>}</>}

export default function App(){const[page,setPage]=useState<Page>('Overview'),[menu,setMenu]=useState(false),[optimized,setOptimized]=useState(false);const content=useMemo(()=>{if(page==='Overview')return <Overview setPage={setPage}/>;if(page==='Optimizer')return <Optimizer onOptimized={()=>setOptimized(true)}/>;if(page==='Scenarios')return <Scenarios/>;if(page==='Analytics')return <Analytics/>;return <Reports/>},[page]);return <div className="app"><Sidebar page={page} setPage={setPage} open={menu} setOpen={setMenu}/>{menu&&<div className="backdrop" onClick={()=>setMenu(false)}/>}<main><Topbar page={page} onMenu={()=>setMenu(true)}/><div className="content" key={page}>{content}</div></main>{optimized&&<div className="toast"><Check/>Optimal solution found in 0.84 seconds<button onClick={()=>setOptimized(false)}><X/></button></div>}</div>}
